extends: spectral:oas
rules:
  info-contact: off
  operation-2xx-response: warn
  operation-operationId-unique: error
  operation-operationId: warn
  operation-tag-defined: warn
  oas3-unused-component: warn

